export const LEGAL_DOCUMENT_TYPES = {
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
} as const;

export type LegalDocumentType = (typeof LEGAL_DOCUMENT_TYPES)[keyof typeof LEGAL_DOCUMENT_TYPES];

export const SIGNUP_REQUIRED_LEGAL_DOCUMENT_TYPES: LegalDocumentType[] = [
  LEGAL_DOCUMENT_TYPES.TERMS_AND_CONDITIONS,
  LEGAL_DOCUMENT_TYPES.PRIVACY_POLICY,
];
