server {
    listen 80;
    server_name indianpgmanagement.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name indianpgmanagement.com;

    ssl_certificate /etc/letsencrypt/live/indianpgmanagement.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/indianpgmanagement.com/privkey.pem;

    return 301 https://www.indianpgmanagement.com$request_uri;
}
