version = 5.4.0
archive_dir = /etc/letsencrypt/archive/ipms-mob-api.pgmanagement.site
cert = /etc/letsencrypt/live/ipms-mob-api.pgmanagement.site/cert.pem
privkey = /etc/letsencrypt/live/ipms-mob-api.pgmanagement.site/privkey.pem
chain = /etc/letsencrypt/live/ipms-mob-api.pgmanagement.site/chain.pem
fullchain = /etc/letsencrypt/live/ipms-mob-api.pgmanagement.site/fullchain.pem
[renewalparams]
account = 3db61d62bb1d26aa5699a84f915a03cf
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
ipms-mob-api.pgmanagement.site = /var/www/certbot
